### ISSUE TITLE
Correct Readme And the Definition of the Project

### ISSUE THREAD

**Issue by 1stdevfriend** [JohnnyJAT/OCR-Tool-for-PrivateMessenger#2]
Remove Minor 2 Project and its description from the project and Correct the introduction of Readme.md. It's still unclear. Make a new readme and ask other people to read it. If they get the same meaning as to what you are developing then it's okay. Since it's very vague right now. 

In Installation, I'll give you the pull request. No worries. 
P.S - Spelling of Kartikay is Kartikey :)
Once done, Set this issue as fixed.

**Comment by JohnnyJAT** [comment]
ok i'll do it
